### ISSUE TITLE
Feature Request: remove the [Folder to search] from the displayed path

### ISSUE THREAD

**Issue by mstaveley** [GabZach/ArtSaver#10]
When [Show image...] [name] and [path] are selected the first data line contains the full path of the image.  I would like an option that would remove from the front of the path the [Folder to search] folder.

For example, if [Folder to search] is /net/host/shared/photos, with subfolders 2021 and 2021-Christmas the first data line would be
    /net/host/shared/photos/2021/2021-Christmas/img001
while what I would like is
    2021/2021-Christmas/img001

Thanks for your consideration

**Comment by GabZach** [comment]
I used to do that, but what should i display in cases where the folder (or a sub-folder) contains symbolic links or aliases? They could point anywhere in the filesystem.

**Comment by mstaveley** [comment]
If the [Folder to search] is not on the front of the path, then print the whole path.

Another option is to have a list input like you do for [Skip images], that are regex's that are removed from the path.  In this case I would like them removed from anywhere in the path, and all regex's are run, so I could remove something from both the start and the end of the path (or even the middle). 

Thanks for considering this.

**Comment by GabZach** [comment]
> 
> If the [Folder to search] is not on the front of the path, then print the whole path.

I'll put that on the to-do list - thanks for the suggestion!


Best regards, Gabriel

**Comment by mstaveley** [comment]
I'm a professional programmer, if you want help.

**Comment by GabZach** [comment]
Cool - I'd appreciate that a lot.
If you could send me your email address directly - you can find it in ArtSaverApp under Preferences / Feedback, that would make communication easier.


Best regards, Gabriel

**Comment by GabZach** [comment]
Done.
