### ISSUE TITLE
Screensaver Option can't be open

### ISSUE THREAD

**Issue by ghost** [GabZach/ArtSaver#3]
after installing the screensaver and allow the data protection it will not open the screen saver option. 

iMac and Mac mini
macOS Catalina 10.15.5 (19F96)

**Comment by GabZach** [comment]
Sorry to hear that.

Could you please send screenshots of the steps?

Also, can you please try deleting ArtSaver and downloading this version:

https://owncloud.informatik.uni-bremen.de/index.php/s/NzR9MPXBCHAnbQf
https://owncloud.informatik.uni-bremen.de/index.php/s/W94RBmaKyeP8YFk


Best regards, Gabriel

**Comment by ghost** [comment]
a small video of the problem
https://youtu.be/UlkadtNJNUY

Will now try your links.

**Comment by ghost** [comment]
New Version is working. Thanks a lot :) 
Great work!

**Comment by redburn** [comment]
I had the same problem with the file available on your website, the version linked above fixed it. Maybe it'd be good to update the version on the website?

EDIT: Never mind, I see you're working on the release of the final version 3.1.

**Comment by GabZach** [comment]
I guess , you are right, I put the beta on the web page.  The final version might take a few more weeks as I am working on a helper app right now.
