### ISSUE TITLE
Multiple monitors don't quite work when they're the exact same type

### ISSUE THREAD

**Issue by wheee** [GabZach/ArtSaver#5]
Hi,

Probably in the minority here, but I have my MacBook Pro 16" 2019 attached to 4x 27" wide screen monitors + the retina display.  

(2 directly from the MacBook Pro, and 2 from a hub)

3 of the 27" wide screen monitors are the exact same monitor (ie. Dell U2719D) and in the System Preferences -> Displays, they show up as "DELL U2719D", "DELL U2719D (1)" and "DELL U2719D (2)".

In ArtSaver -> Screen Saver Options -> in the drop down, they all appear a bit differently:
"DELL U2719D"
"DELL U2719D_722495451"
"DELL U2719D_722470109"

After setting them all to different directories, and trying the preview (or waiting for the screen saver to activate), 2 of the 3 27" monitors will show a blank screen at the text: "Change pics folder in System ... for monitor DELL U2719D".  The monitor that is marked as "DELL U2719D" does display images... 

![Screen Shot 2020-07-31 at 5 37 51 PM](https://user-images.githubusercontent.com/516324/89079503-a5c3af00-d354-11ea-9331-b027ec6206f3.png)
![Screen Shot 2020-07-31 at 5 37 48 PM](https://user-images.githubusercontent.com/516324/89079507-a65c4580-d354-11ea-97d3-c5a45173bf8c.png)
![Screen Shot 2020-07-31 at 5 37 42 PM](https://user-images.githubusercontent.com/516324/89079509-a6f4dc00-d354-11ea-96cd-ad60e6de945b.png)
![Screen Shot 2020-07-31 at 5 37 01 PM](https://user-images.githubusercontent.com/516324/89079510-a6f4dc00-d354-11ea-894b-63623c3428ff.png)

**Comment by GabZach** [comment]
Hi James,

thanks a lot for writing.
Your setup is challenging (I haven't heard from a user with that many monitors :-) ),
but I'd love to try to make ArtSaver work for that setup.

First of all, what macOS are you using? Mojave or Catalina?

Second,  could you please run the screensavers (just move your mouse into the hot corner that launches the screensaver), then send me the log file.
I can send instructions how to do that, if you are unsure.


Best regards, Gabriel

**Comment by wheee** [comment]
Hi Gabriel,

Thanks for responding and more than happy to help stress test the multi-monitor setup!  (If you want me to shamelessly show pictures of my workstation setup I can... it's pretty darn cool and one of a kind)

In any case... I'm using Catalina.

And as per the manual, I'm attaching the logs from using the command:
log show --predicate 'subsystem == "de.zach.ArtSaver"' --info

[artsaver_logs.txt](https://github.com/GabZach/ArtSaver/files/5010921/artsaver_logs.txt)

**Comment by GabZach** [comment]
Hi James,

> (If you want me to shamelessly show pictures of my workstation setup I can... it's pretty darn cool and one of a kind)

Yes, please do send a picture - I am always curious about ArtSaver users' setups :-)

> artsaver_logs.txt <https://github.com/GabZach/ArtSaver/files/5010921/artsaver_logs.txt>
> 

Thanks so much -  will try to analyze them ASAP (right now i'm on vacation)

Best regards, Gabriel

**Comment by wheee** [comment]
Thanks Gabriel. I'll be happy to test out any new builds... be great to be able to get all 4 monitors displaying the screen saver.  But do enjoy your vacation!

![IMG_9064](https://user-images.githubusercontent.com/516324/89355844-65cd3680-d68a-11ea-9831-88c771dc8e03.jpg)
![IMG_9062](https://user-images.githubusercontent.com/516324/89355850-68c82700-d68a-11ea-99b3-6e93f7a9aeab.jpg)

**Comment by GabZach** [comment]
Wow! Really an impressive setup! 
And an impressive office (or is it your living room? ;-) )

Best regards, Gabriel

**Comment by wheee** [comment]
It's my home office - which is also my den in my condo.  Even before this pandemic hit, I've been working from home for a few years consulting although I use a different laptop for that.

But I've been transitioning to indie game dev in the past 2 years so this is the primary work station for coding and game engine work.

**Comment by ranbo** [comment]
I'm having the same problem. I have two 27" 4K Dell monitors of the same model as each other. The screen saver options list two different IDs for the two monitors, but no matter what folder I pick, it still says "Change pics folder..."

I have tried unplugging one monitor so that there's just one, and still the same problem. The images show up in the screensaver preview, but not when I use the hot corners to launch the screensaver.

**Comment by GabZach** [comment]
I have fixed (or at least tried to fix) this bug in version 3.1 (August 2020).
So, multiple monitors with the same name / brand / model should not be any problem any more.

I suspect, the problem you are experiencing has a different cause. I will get in touch with you via email.

**Comment by GabZach** [comment]
Fixed (hopefully)
